# Generated by Django 6.0 on 2025-12-29 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("productor", "Productor"),
                            ("agente_carga", "Agente de carga / Forwarder"),
                            ("naviera", "Naviera"),
                            ("puerto", "Puerto / Terminal"),
                            ("aduana", "Agencia de aduana"),
                            ("transporte_local", "Transportista local"),
                            ("bodega", "Bodega / Depósito"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=30,
                    ),
                ),
                ("contacto", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("notas", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Importacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Contenedor Tianjin Sep-2025",
                        max_length=120,
                    ),
                ),
                (
                    "incoterm",
                    models.CharField(
                        choices=[
                            ("EXW", "EXW"),
                            ("FOB", "FOB"),
                            ("CIF", "CIF"),
                            ("CFR", "CFR"),
                            ("DDP", "DDP"),
                        ],
                        default="FOB",
                        max_length=10,
                    ),
                ),
                (
                    "pol",
                    models.CharField(
                        blank=True, help_text="Puerto origen (POL)", max_length=80
                    ),
                ),
                (
                    "pod",
                    models.CharField(
                        blank=True, help_text="Puerto destino (POD)", max_length=80
                    ),
                ),
                (
                    "kilos_estimados",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "moneda_base",
                    models.CharField(
                        default="CLP", help_text="CLP / USD / CNY", max_length=10
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("origen", "Origen"),
                            ("internacional", "Internacional"),
                            ("destino", "Destino / Puerto"),
                            ("aduana", "Aduana"),
                            ("local", "Local (Chile)"),
                            ("financiero", "Financiero"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=250)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Forwarder A + Puerto Lirquén + Transp X",
                        max_length=120,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "importacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cotizaciones",
                        to="importaciones.importacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CotizacionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("moneda", models.CharField(default="CLP", max_length=10)),
                (
                    "tipo_cambio",
                    models.DecimalField(decimal_places=4, default=1, max_digits=14),
                ),
                ("aplica_iva", models.BooleanField(default=True)),
                (
                    "iva_pct",
                    models.DecimalField(decimal_places=2, default=19, max_digits=5),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="importaciones.cotizacion",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="importaciones.empresa",
                    ),
                ),
                (
                    "tipo_costo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="importaciones.tipocosto",
                    ),
                ),
            ],
        ),
    ]
