# Generated by Django 6.0 on 2025-12-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacion",
            name="kilos_merma",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Kilos perdidos por rotura, humedad, polvo, etc.",
                max_digits=12,
            ),
        ),
    ]
