# Generated by Django 6.0.1 on 2026-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importaciones", "0002_importacion_kilos_merma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacionitem",
            name="monto",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="cotizacionitem",
            name="tipo_cambio",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
        ),
        migrations.AlterField(
            model_name="importacion",
            name="kilos_estimados",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="importacion",
            name="moneda_base",
            field=models.CharField(default="CLP", help_text="CLP ", max_length=10),
        ),
    ]
